### ISSUE TITLE
Nem lehet lebuildelni.

### ISSUE THREAD

**Issue by pirosgyb2** [BME-MIT-IET/Raketa-iet-2018#1]
Vagy valahogy updateljük a projektet vagy pedig az android studio gradle szintjét kéne lejjebb venni.

**Comment by kkanga** [comment]
![image](https://user-images.githubusercontent.com/33024059/39593530-567f9b64-4f0a-11e8-8de7-e39d7bbddb1e.png)
Ide szúrjátok be ezt a fájlt, amit generáltam:

[google-services.txt](https://github.com/BME-MIT-IET/Raketa-iet-2018/files/1972038/google-services.txt)
írjátok át json-re!

**Comment by Sajtosstangli** [comment]
Alkalmazás leellenőrizve, működik.

**Comment by Sajtosstangli** [comment]
**Commit link:**
https://github.com/BME-MIT-IET/Raketa-iet-2018/commit/5ac7e8dddf51ef89211fac491df2cd84b40c951f
