### ISSUE TITLE
Manuális tesztek tervezése

### ISSUE THREAD

**Issue by kkanga** [BME-MIT-IET/Raketa-iet-2018#13]

**Comment by kkanga** [comment]
_Amiket csináltam:_

**Bejelentkezés, felhasználó létrehozása:**

- Új felhasználó sikeres hozzáadása
- Foglalt e-mail címmel történő regisztráció
- Helytelen e-mail formátummal történő regisztráció
- Túl rövid jelszóval való regisztráció
- Hiányzó jelszóval történő regisztráció
- Hosszú jelszó megadása regisztrációkor
- Kijelentkezés

**Kategóriákkal kapcsolatos tesztek:**

- Új kategória létrehozása
- Kategória létrehozása név nélkül
- Kategória létrehozása ikon nélkül

**Tételek**:

- Tétel létrehozása
- Analízis több tétel esetén

**Alkalmazástéma:**

- Alkalmazás témájának átállítása

**Comment by pirosgyb2** [comment]
Mindegyik kész.
