### ISSUE TITLE
Manuális tesztek végrehajtása és dokumentálása

### ISSUE THREAD

**Issue by kkanga** [BME-MIT-IET/Raketa-iet-2018#14]

**Comment by kkanga** [comment]
A kapcsolódó wiki oldalt kitöltöttem, és a hozzá tartozó képeket a  #12 pull requestben és az "Adding images for wiki site - test" (c6c4c61f22886b756397b7cf0cca943337bc599a, branching előtt) commitban adtam hozzá az alkalmazáshoz.

**Comment by pirosgyb2** [comment]
Kész a feladat, minden OK.
