### ISSUE TITLE
Appba bejelentkezés

### ISSUE THREAD

**Issue by pirosgyb2** [BME-MIT-IET/Raketa-iet-2018#4]

**Comment by pirosgyb2** [comment]
Készíteni kellett egy firebase appot, aminek az Authethentiacationnél az anyonymoust és a email/password-öt be kellett kapcsolni, majd legenerálni a google-service.js fájlt. Ezzel már be tudunk jelentkezni az appba.

**Comment by pirosgyb2** [comment]
commit: 2bab27da851b8e2f185dfccb0f188c0272f93acf

**Comment by Sajtosstangli** [comment]
A feladat elkészült, az alkalmazásba sikeresen be lehet jelentkezni.
