### ISSUE TITLE
Manuális kód átvizsgálás

### ISSUE THREAD

**Issue by NacsaPeter** [BME-MIT-IET/Raketa-iet-2018#5]

**Comment by NacsaPeter** [comment]
Kódot átnéztük. Modellek felépítése átlátható. Megjelenítési osztályok működése nem egyértelmű, de követhető. Külső osztályokat nem találtuk meg. Projekt struktúrája kissé zavaros.

**Comment by NacsaPeter** [comment]
Megterveztük az átvizsgálás részleteit. A vizsgálat célja az objektum orientált tervezési elvek és tervezési heurisztikák megsértésének kiszűrése a karbantarthatóság érdekében.

**Comment by NacsaPeter** [comment]
Összegyűjtöttük a jellemző problémákat és készítettünk hozzájuk megoldási javaslatokat.

**Comment by NacsaPeter** [comment]
@pirosgyb2 törölte az outlay mappát ([ac7461f](https://github.com/BME-MIT-IET/Raketa-iet-2018/pull/9/commits/93a8cd9463ea1cb1b0ea6435d6efa09aec82c4fe)), majd visszahelyezte ([ac7461f](https://github.com/BME-MIT-IET/Raketa-iet-2018/pull/9/commits/ac7461f274b172e4c9ddfd68ba93f7ddb1737482)) és kért egy pull requestet [#9](https://github.com/BME-MIT-IET/Raketa-iet-2018/pull/9). A változtatások alapján megírtam az egyes kódrészletekhez a megoldási javaslatokat.

**Comment by NacsaPeter** [comment]
A feladathoz tartozó [wiki oldal](https://github.com/BME-MIT-IET/Raketa-iet-2018/wiki/Manu%C3%A1lis-k%C3%B3d-%C3%A1tvizsg%C3%A1l%C3%A1s) elkészült.

**Comment by Sajtosstangli** [comment]
A feladat elkészült és átnézve.
