### ISSUE TITLE
BDD tesztek készítése: Cucumber

### ISSUE THREAD

**Issue by NacsaPeter** [BME-MIT-IET/Raketa-iet-2018#7]

**Comment by pirosgyb2** [comment]
E lírás alapján, sikerült hozzáadnom a projekthez a Cucumbert. [link](https://proandroiddev.com/be-da-developer-cucumber-on-android-cfd07773e59d) Az app szintű build.gradle fájlban androidTestCompile helyett compile-t írtam, mert különben az Instruments.java fájlban nem tudtam beimportolni a szükséges dolgokat.

**Comment by pirosgyb2** [comment]
Több probléma is volt ezután, amit nem tudtam megoldani, valamit elronthattam az app szintű build.gradle fájlban ezért kezdtem egy új branchet a masterről Cucumber2 néven.

**Comment by pirosgyb2** [comment]
Itt szintén a linkelt leírás alapján megcsináltam újra mindent, de most már az androidTestCompile-ra nem dobott hibát, így nem írtam compile-t helyette. A további hibák eredetére hosszú keresés után jöttem rá. Akkor volt probléma ha a behivatkozott könyvtár Java8-as elemekt akart használni. Ehhez a Cucumberhez szükséges 4 behivatkozott könyvtárhoz meg kellett nézni, hogy melyiknek melyik  az az 
 utolsó verziója, ami még nem használ Java8-at. A build.gradle-be már eszerint írtam a verziószámokat. Így már erre nem dobott hibát.

**Comment by pirosgyb2** [comment]
Ezután elkészítettem az első feature fájlt. És a Steps Java fájlt. A Guestként való belépést akartam tesztelni, de több nehézségbe is ütköztem. 

Az egyik, hogy az espresso-nem kezeli azt hogy várni kell amíg a válasz megérkezik a szervertől, így ezt is kezelni kellett volna valahogy, ezt nem tudtam megírni. 

Továbbá a loginhoz a LoginActivityt kellett megadni a Steps fájlban, hogy innen induljon. Ez egy fragmentet nyit meg, amibe behív egy másik fájlban definiált RealtiveLayoutot aminek az egyik gombja a Guest feliratú button. Ezt sehogy sem tudtam elérni az espresso kifejezésekkel. Hiába kerestem, nem tudta megoldani.

Ehelyett két egyszerűbb tesztet írtam meg. Az egyik teszteli ,hogy  ha a főoldalon a jobb felső Chart ikonra kattintunk akkor tényleg megjelenik-e a Charts oldal. A másik pedig azt ellenőrzi, hogy ha lenyomunk egy gombot a főoldalon akkor az értéke megjelenik-e a felül a dobozban.

**Comment by pirosgyb2** [comment]
Ezek sikeresen lefutottak. 
Commit: 21bb8936b4999c92a414e8e053463277fefad120

**Comment by pirosgyb2** [comment]
Ezután mergeltük: a23aecc08b8f5cad74b1238aec66c6b28b8ec5df

**Comment by pirosgyb2** [comment]
A wikis doksit is elkészítettem.

**Comment by Sajtosstangli** [comment]
A tesztek sikeresen lefutottak, a feladat elkészült és ellenőrizve.
