### ISSUE TITLE
Tesztek kódlefedettségének mérése: JaCoCo

### ISSUE THREAD

**Issue by NacsaPeter** [BME-MIT-IET/Raketa-iet-2018#8]
Tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése

**Comment by NacsaPeter** [comment]
JaCoCo plugin beüzemelve.
[`c287ac4`](https://github.com/BME-MIT-IET/Raketa-iet-2018/commit/c287ac4558c6d342babc72361e375da1927e20ed)

**Comment by NacsaPeter** [comment]
A feladathoz tartozó [wiki oldal](https://github.com/BME-MIT-IET/Raketa-iet-2018/wiki/Tesztek-k%C3%B3dlefedetts%C3%A9g%C3%A9nek-m%C3%A9r%C3%A9se) elkészült.

**Comment by pirosgyb2** [comment]
Elkészült minden. Kipróbáltuk, a BDD tesztekkel változtak az eredmények.  Minden jól működik.
